export const GENERATE_TOKEN = 'GENERATE_TOKEN'
export const GENERATE_TOKEN_SUCCESS = 'GENERATE_TOKEN_SUCCESS'
export const GENERATE_TOKEN_ERROR = 'GENERATE_TOKEN_ERROR'
export const API_ERROR = 'API_ERROR'

export const PERSONAL_DETAILS = "PERSONAL_DETAILS"
export const PERSONAL_DETAILS_SUCCESS = "PERSONAL_DETAILS_SUCCESS"
export const PERSONAL_DETAILS_ERROR = "PERSONAL_DETAILS_ERROR"